rvm:
  - 2.1
  - 2.2

branches:
  only:
    - master
    - 4-0-stable
    - 3-2-stable
    - 3-1-stable
    - capybara

before_script:
  - psql -c 'create database typus_test;' -U postgres

env:
  global:
    - DB=postgresql
    - DB_USERNAME=postgres

cache:
  bundler: true
  apt: true
  edge: true
