app_name: Morning Labs
app_description: Web Development for the Masses
site_name: This is the site name
site_description: This is the site description
version: Typus 2.0a
per_page: 15
project_url: http://intraducibles.net/projects/typus