# Catalan (ca) translations for Typus by:
# - Lleïr Borràs <http://github.com/lleirborras>

ca:

  "Actions": "Accions"
  "Active": "Actiu"
  "Add": "Afegir"
  "Add new": "Afegir nou"
  "Are you sure?": "Estàs segur?"
  "Are you sure you want to sign out and end your session?": "Estàs segur que vols sortir i tancar la sessió?"

  "Change %{attribute}?": "Canviar %{attribute}?"
  "Click OK to continue, or click Cancel to stay on this page": "Prem OK per continuar, o prem Cancel·lar per romandre en aquesta página."
  "Create %{resource}": "Crear %{resource}"

  "Dashboard": "Panell de control"
  "Down": "Baixar"

  "Edit": "Editar"
  "Edit %{resource}": "Edit %{resource}"
  "Enter your email below to create the first user": "Introdueix el teu email per crear el primer usuari."

  "False": "Fals"
  "Filter": "Filtrar"
  "Filter by %{attribute}": "Filtrar per %{attribute}"

  "Go to": "Anar a"

  "I remember my password": "Recordo la meva contrasenya"
  "If you didn't request a password update, you can ignore this message": "Si no has demanat una actualització de la teva contrasenya, pots ignorar aquest missatge."
  "If you have made any changes to the fields without clicking the Save/Update entry button, your changes will be lost": "Si has realitzat algun canvi en els camps sense premer el botó Guardar/Actualitzar, els teus canvis es perdran."
  "Inactive": "Inactiu"

  "Last few days": "Últims dies"
  "Last 30 days": "Últims 30 dies"
  "Last 7 days": "Últims 7 dies"
  "List": "Llista"
  "Logged as": "Identificat com"
  "Login": "Login"

  "New": "Nou"
  "New %{resource}": "Nou %{resource}"
  "Next": "Següent"
  "No %{resources} found": "No s'han trobat %{resources}."

  "Options": "Opcions"

  "Password recovery link sent to your email": "L'enllaç de recuperació de contrasenya enviat al teu correu electrònic."
  "Previous": "Anterior"

  "Record moved %{to}": "Registre desplaçat %{to}."
  "Recover password": "Recuperar contrasenya"
  "Remove": "Eliminar"
  "Remove %{attribute}": "Esborrar %{attribute}"
  "Remove %{resource}?": "Esborrar %{resource}?"
  "Remove filter": "Treure filtre"
  "Remove search": "Treure cerca"
  "Reset password": "Canviar contrasenya"
  "Resources": "Recursos"

  "Save %{resource}": "Guardar %{resource}"
  "Search": "Cercar"
  "Search by": "Cercar per"
  "Setup": "Configurar"
  "Show": "Mostrar"
  "Show %{resource}": "Mostrar %{resource}"
  "Sign in": "Entrar"
  "Sign out": "Sortir"
  "Sign up": "Crear compte"
  "System Users Administration": "Administrar usuaris del sistema"

  "That doesn't seem like a valid email address": "Això no sembla ser una adreça de correu electrònic vàlida."
  "Today": "Avui"
  "Toggle is disabled": "Alternar està desactivat."
  "True": "Cert"

  "Unrelate %{resource}?": "Deslligar %{resource}?"
  "Up": "Pujar"

  "You're adding a new %{resource_from}": "Estàs afegint un nou %{resource_from}."
  "You're adding a new %{resource_from} to %{resource_to}": "Estàs afegint un nou %{resource_from} a %{resource_to}."
  "You're not allowed to remove Typus Users": "No pots esborrar usuaris de typus."
  "You're not allowed to toggle status": "No pots canviar el teu estat."
  "You can update your password at": "Pots actualitzar la teva contrasenya a"
  "You can't change your role": "No pots canviar-te tu mateix el rol."
  "You can't remove yourself": "No et pots eliminar a tu mateix."
  "You can't toggle your status": "No pots canviar-te l'estat."
  "You're updating a %{resource_from}": "Estàs actualitzant un %{resource_from}."
  "You're updating a %{resource_from} for %{resource_to}": "Estàs actualitzant un %{resource_from} de %{resource_to}."

  "View all %{attribute}":
  "View site": "Veure la web"

  "%{attachment} removed": "%{attachment} esborrat."
  "%{current_user_role} is not able to perform this action. (%{action})":
  "%{model} filtered by %{filtered_by}": "%{model} filtrats per %{filtered_by}"
  "%{model} successfully created": "%{model} satisfactòriament creat."
  "%{model} successfully removed": "%{model} satisfactòriament eliminat."
  "%{model} successfully updated": "%{model} satisfactòriament actualitzat."
  "%{model_a} successfully assigned to %{model_b}": "%{model_a} assignat satisfactòriament a %{model_b}."
