de:
  activerecord:
    models:
      admin_user:
    attributes:
      admin_user:
        email:
        first_name: "Vorname"
        last_name: "Nachname"
        password: "Passwort"
        password_confirmation: "Passwort Best&auml;tigung"
        status:
        role:
