hu:
  activerecord:
    models:
      admin_user:
    attributes:
      admin_user:
        email:
        first_name: "Vezetéknév"
        last_name: "Keresznév"
        password: "Jelszó"
        password_confirmation: "Jelszó megerősítés"
        status: "Státusz"
        role: "Jogosultsági szint"
