it:
  activerecord:
    models:
      admin_user:
    attributes:
      admin_user:
        email:
        first_name: "Nome"
        last_name: "Cognome"
        role: "Ruolo"
        status: "Stato"
        preferences: "Preferenze"
        language: "Lingua"
        password: "Password"
        password_confirmation: "Ripeti la password"
