# Portuguese (pt-BR) translations for Typus by:
# - George Guimarães <http://github.com/georgeguimaraes>

pt-BR:

  "Actions": "Ações"
  "Active":
  "Add": "Adicionar"
  "Add new": "Adicionar novo"
  "Are you sure?":
  "Are you sure you want to sign out and end your session?": "Tem certeza que quer sair e encerrar sua sessão?"

  "Change %{attribute}?": "Mudar %{attribute}?"
  "Click OK to continue, or click Cancel to stay on this page": "Clique OK para continuar, ou clique em Cancelar para ficar nesta página."
  "Create %{resource}": "Criar %{resource}"

  "Dashboard": "Painel"
  "Down": "Descer"

  "Edit": "Editar"
  "Edit %{resource}": "Editar %{resource}"
  "Enter your email below to create the first user": "Escreva seu email para criar o primeiro usuário"

  "False": "Falso"
  "Filter": "Filtrar"
  "Filter by %{attribute}": "Filtrar por %{attribute}"

  "Go to": "Ir a"

  "I remember my password": "Lembro minha senha"
  "If you didn't request a password update, you can ignore this message": "Se você não pediu uma renovação de senha, por favor ignore esta mensagem."
  "If you have made any changes to the fields without clicking the Save/Update entry button, your changes will be lost": "Se você fez alterações nos campos e não clicou no botão de Salvar/Atualizar, suas alterações serão perdidas"
  "Inactive":

  "Last few days": "Últimos dias"
  "Last 30 days": "Últimos 30 dias"
  "Last 7 days": "Últimos 7 dias"
  "List":
  "Logged as": "Logado como"
  "Login": "Login"

  "New": "Novo"
  "New %{resource}": "Novo %{resource}"
  "Next": "Próximo"
  "No %{resources} found":

  "Options": "Opções"

  "Password recovery link sent to your email": "Link para recuperar senha enviado para seu email."
  "Previous": "Anterior"

  "Record moved %{to}": "Registro movido %{to}."
  "Recover password": "Recuperar senha"
  "Remove": "Remover"
  "Remove %{attribute}": "Remover %{attribute}"
  "Remove %{resource}?": "Remover %{resource}?"
  "Remove filter": "Remover filtro"
  "Remove search":
  "Reset password": "Trocar senha"
  "Resources": "Recursos"

  "Save %{resource}":
  "Search": "Busca"
  "Search by": "Buscar por"
  "Setup": "Configurar"
  "Show": "Mostrar"
  "Show %{resource}": "Mostrar %{resource}"
  "Sign in": "Entrar"
  "Sign out": "Sair"
  "Sign up": "Criar conta"
  "System Users Administration": "Administrar usuários do sistema"

  "That doesn't seem like a valid email address": "Este não parece um email válido"
  "Today": "Hoje"
  "True": "Verdadeiro"

  "Unrelate %{resource}?": "Desvincular %{resource}?"
  "Up": "Subir"

  "View all %{attribute}":
  "View site": "Ver site"

  "You're updating a %{resource_from} for %{resource_to}": "Você está atualizando um %{resource_from} de %{resource_to}."
  "You're updating a %{resource_from}": "Você está atualizando um %{resource_from}."
  "You can't toggle your status": "Você não pode mudar seu status."
  "You're not allowed to toggle status": "Você não está autorizado a mudar o status."
  "You can't remove yourself": "Você não pode apagar a si mesmo."
  "You're not allowed to remove Typus Users": "Você não está autorizado a apagar usuários do sistema."
  "You can update your password at": "Você pode atualizar sua senha em"
  "You can't change your role": "Você não pode mudar sua própria função no sistema."

  "%{current_user_role} is not able to perform this action. (%{action})":
  "%{model} filtered by %{filtered_by}": "%{model} filtrados por %{filtered_by}"
  "%{model} successfully created": "%{model} criado com sucesso."
  "%{model} successfully removed": "%{model} removido com sucesso."
  "%{model} successfully updated": "%{model} atualizado com sucesso."
  "%{model_a} successfully assigned to %{model_b}": "%{model_a} atribuído com sucesso a %{model_b}."
