pt-BR:
  activerecord:
    models:
      admin_user: "Usuário do sistema"
    attributes:
      admin_user:
        email:
        first_name: "Primeiro nome"
        last_name: "Sobrenome"
        password: "Senha"
        password_confirmation: "Senha confirmação"
        status:
        role:
